### ISSUE TITLE
error icon launcher

### ISSUE THREAD

**Issue by winzaldi** [Gavras/MultiLineRadioGroup#6]
the icon launcher from the multilineradiogroup was replace the icon_launcher from project, so ai create the new icon launcher and changed name new icon , but i get error like bellow . please help.

Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@icon value=(@mipmap/ic_launcher_psks) from AndroidManifest.xml:15:9-48
  	is also present at [com.github.Gavras:MultiLineRadioGroup:v1.0.0.4] AndroidManifest.xml:13:9-43 value=(@mipmap/ic_launcher).
  	Suggestion: add 'tools:replace="android:icon"' to <application> element at AndroidManifest.xml:13:5-49:19 to override.

**Comment by Gavras** [comment]
Ok, there were some redundant files in the library.
I added a new release [(here)](https://github.com/Gavras/MultiLineRadioGroup/releases/tag/v1.0.0.6) please tell me if the error is fixed after this release.

**Comment by winzaldi** [comment]
Thanks Gavras, it work..:)
